# Generated by Django 3.1.5 on 2021-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreportcard',
            name='category',
        ),
        migrations.AddField(
            model_name='studentreportcard',
            name='date',
            field=models.DateField(default='2021-07-24'),
            preserve_default=False,
        ),
    ]
